---
title: "US Weather Effects on Population Health and the Economic Consequences"
output: html_document
---

## Synopsis
In this report we aim to describe which type of US weather events are most harmful with respect to population health and which have the greatest economic consequences.

--------------------------------------------------------------------------------

## Data Processing

### Reading in the data
We first read in the data from the csv file in [Storm Data](https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2) 47mb bz2 file, as specified in the assignment. 
```{r}
orig.storms <- read.csv("data/repdata-data-StormData.csv", stringsAsFactors=FALSE)
```

After reading in the data we see that there are 902297 observations (rows) and 37 variables (columns) in this dataset.
```{r}
dim(orig.storms)
```

We survey the first few rows in this dataset.  These documents help us find how some of the variables are constructed/defined.

  - National Weather Service [Storm Data Documentation](https://d396qusza40orc.cloudfront.net/repdata%2Fpeer2_doc%2Fpd01016005curr.pdf)
  - National Climatic Data Center Storm Events [FAQ](https://d396qusza40orc.cloudfront.net/repdata%2Fpeer2_doc%2FNCDC%20Storm%20Events-FAQ%20Page.pdf)

```{r}
head(orig.storms)
```

Reducing the dataset from 37 variables to only those variables we are focusing on helps improve subsequent computational performance.  Besides EVTYPE, the following variables are needed.

  - Population health: FATALITIES, INJURIES
  - Economic consequences: PROPDMG, PROPDMGEXP, CROPDMG, CROPDMGEXP
  
```{r}
storms <- orig.storms[,c("EVTYPE",
                         "FATALITIES", "INJURIES",
                         "PROPDMG", "PROPDMGEXP",
                         "CROPDMG", "CROPDMGEXP")]
dim(storms)
```

There are 985 different event types `EVTYPE`.
```{r}
unique(storms$EVTYPE)
```

--------------------------------------------------------------------------------

## Results

```{r}
plot(cars)
```
